require("packs/homepage/bootstrap/jquery-3.5.1.slim.min")
require("packs/homepage/bootstrap/popper.min")
require("packs/homepage/bootstrap/bootstrap.min")
require("packs/homepage/owl.carousel")
require("packs/homepage/carousel")